name: Build, tag, push

on:
  release:
    types: [published]


jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: "blairnangle"
      IMAGE_NAME: "$DOCKERHUB_USERNAME/python3-numpy-ta-lib"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set image version from git tag
        run: echo "IMAGE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build image and tag as latest
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Tag image with version number
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}

      - name: Push the tagged-with-version number image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Push the tagged-with-latest image
        run: docker push ${{ env.IMAGE_NAME }}:latest
